### PR TITLE
Use an actual .env for environmental variables

### PR DESCRIPTION
**Pull request by LightArrowsEXE**
Use a proper .env file to load in specific default arguments. This is preferable to having them in a separate python file (unless you need to perform some kind of advanced checks on the values).

### CODE REVIEW

**Comment by Mr-Z-2697** [comment]
This loads .env values into system environment variables but not into python variables.

**Comment by Mr-Z-2697** [comment]
That problem can be easily solved, of course.
But I'm wondering is there a *clean (more on that later)* way to have a "global" configuration, like in current state, importing a python file means it works for this entire python installation (or venv, portable, whatever), but python-dotenv just searchs parent folders (till root).
(except just have these environment variables set in the system to begin with, that's an obvious solution but I think kinda messy)

**Comment by LightArrowsEXE** [comment]
> This loads .env values into system environment variables but not into python variables.

Oops, you're right. My bad, I'll fix this in a minute.

> That problem can be easily solved, of course. But I'm wondering is there a _clean (more on that later)_ way to have a "global" configuration, like in current state, importing a python file means it works for this entire python installation (or venv, portable, whatever), but python-dotenv just searchs parent folders (till root). (except just have these environment variables set in the system to begin with, that's an obvious solution but I think kinda messy)

You're right, I didn't really think about this issue. One way to maybe resolve this is to point directly to the directory of the package itself and read the .env file from there? Another would be to simply make most of these parameters and/or functions that automatically try to guess which to use based on the user's system, kinda like how some packages check if you have a specific GPU type or something.

The issue with doing it the way it is now is that users MUST change a file that will be reverted every time they decide to update. Admittedly the .env file has the same problem right now, but it's easy to work around (simply have it write a new file if it doesn't exist, and don't package it with the script directly, to name one example. Or the more sensible thing, which would be to just try to read it and otherwise fall back to defaults if it simply doesn't exist, and maybe make a note in the README).

**Comment by LightArrowsEXE** [comment]
I'd also consider making this a proper package. Right now to get this working, you have to have it read a .env file in `site-packages`, which may be polluted with other vars. But that's something to consider tackling in a different PR.

**Comment by Mr-Z-2697** [comment]
> I'd also consider making this a proper package. Right now to get this working, you have to have it read a .env file in `site-packages`, which may be polluted with other vars. But that's something to consider tackling in a different PR.

Considering the structure of this script, I think turning it to a package is not a primary task.
Maybe not use ".env" alone as file name, use ".env.zvs" or something?
And perhaps we can load .env again from project folder to override the global ones.

**Comment by LightArrowsEXE** [comment]
> Maybe not use ".env" alone as file name, use ".env.zvs" or something? And perhaps we can load .env again from project folder to override the global ones.

Yeah, that might be the best idea if you're not turning this into a package. I'd also make a note in the README about this, but I think it's probably better for you to write that.

**Pull request merged**
